### ISSUE TITLE
Sidebar cuts at the bottom (beta)

### ISSUE THREAD

**Issue by mkz212** [oznu/homebridge-config-ui-x#2110]
On iPhone it cuts sidebar when scrolling. 

https://github.com/user-attachments/assets/1886e293-0a83-426f-9b17-ac94d8599769

Some kind of workaround is:

```css
.header {
  position: fixed !important;
  overflow: hidden;
  top: 0;
  left:0;
}

.sidebar {
  position: fixed !important;
  overflow: hidden;
  top: 0;
  left: 0;
}

  .sidebar .link-wrapper {
  position: fixed !important;
  top: 80px;
  overflow-y: auto;
}

```
